### ISSUE TITLE
Total Portfolio Values

### ISSUE THREAD

**Issue by goodtaster** [CounterpartyXCP/counterwallet#493]
It's hard to keep track of total BTC/XCP if they are spread across many addresses. I propose to show BTC and XCP totals on the main wallet page.

**Comment by rippler** [comment]
@goodtaster totals for non-BTC and XCP will be hard. I think some 6 months ago Ouziel commented that it's very difficult to do if the asset hasn't been traded on DEx for a while (on coinmarketcap.com you can see that the difference between centralized exchanges and DEx price of some assets can be 50% or more because the last trade (and price) from DEx may be days old, and some assets don't have any transactions on DEx as they haven't traded at all).

**Comment by goodtaster** [comment]
Totals for XCP should not be that hard:
XCP on address 1 + XCP on address 2 + etc.

I agree that assets should be left out entirely in this, and edited my original post to reflect this.

**Comment by robby-dermody** [comment]
portfolio page will be removed (for now), so closing this
