### ISSUE TITLE
Does it still make sense to keep the Chat feature?

### ISSUE THREAD

**Issue by brighton36** [CounterpartyXCP/counterwallet#726]
Perhaps it makes more sense to instead provide a prominent link to the counterpartytalk.org forums. The conversations in the Chat aren't being manned by anyone competant best that I can tell, and I don't think people are using it to solve problems. Perhaps we could have a little 'Have Questions?' interface where the top N forum posts are displayed from the https://counterpartytalk.org/c/support/product-support category?

**Comment by robby-dermody** [comment]
@rippler , @ivanaszuber, @ouziel-slama, @niceplum, any thoughts?

**Comment by ivanaszuber** [comment]
+1 for the 'Have Questions' proposal. I don't have a strong opinion about removing the chat, but since none of us monitor it frequently maybe best to shut it down and just link to the forum.

**Comment by ouziel-slama** [comment]
+1 to remove the chat

**Comment by rippler** [comment]
+1, I like the idea.

**Comment by cryptonaut420** [comment]
+1 as well, all I ever see in the chat is people being confused or complaining about bugs (with usually no one to help) and that Barron guy who loves to troll and constantly advertise shitty old MPEx

**Comment by robby-dermody** [comment]
+1, I'm in favor as well.

* We can easily remove the "Chat" tab, for starters. Between the "Page Help" button on some pages and the question mark icon at the upper right (which will be adjusted to remove mention of chat), I'm thinking we will be covered.
* Perhaps highlight/color the question mark logo to make it stick out?
* We can also provide a link on that help window that appears to the top questions.

Comments/alterations to this?

**Comment by ivanaszuber** [comment]
I agree with everything listed and with coloring the question mark (maybe the same green as the Page Help?). Or even better, combine the Page Help and the question mark into a single pop-up (the two seem redundant) and have it in the upper menu?

**Comment by goodtaster** [comment]
+1. It does not necessarily feel reassuring to have a chat inside your 'wallet', whatever the actual security implications may be. We can link people to the Gitter chat as well..

+1 I agree with Ivana to make the question mark green Also I wouldn't say they are redundant, because depending on the individual, they may be more likely to notice either the visual or textual representation of it.

* I also think we can add some more simple descriptions (2-3 sentences) on some of the pop-ups. Otherwise it may seem a bit cryptic, even with the help documents available. (E.g. for multi-sig features and transaction signing)

**Comment by ouziel-slama** [comment]
I remove the chat and made the question mark green here: https://github.com/CounterpartyXCP/counterwallet/commit/35d830a2a9cc4e20b20a9565429b941f25586199
