### ISSUE TITLE
DEx order not visible in CW Markets

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterwallet#741]
1. XCPCARD / XCP buy order issued via CW (buy 1 XCPCARD for 3 XCP)
2. XCPCARD buy order is not visible in XCPCARD / XCP market (Buy orders) in CW
3. The same order is visible on DEx when viewed from blockscan.com: 
http://blockscan.com/orderinfo/11715092

**Comment by romeshomey** [comment]
I have found several assets with this same issue.   It would be helpful if there was a hint of resolution to it after so much time passing.  I have had this open thread on this issue at counterpartytalk since around the same time you posted the issue here.

https://counterpartytalk.org/t/order-not-showing-up-in-xcpcard-xcp-market/1411

**Comment by robby-dermody** [comment]
this may be due to the feed being broken with current production counterwallet. the issue has been fixed in https://github.com/CounterpartyXCP/counterwallet/commit/fed6bfdb1ea2d5c6240cae94e8105b3b3d78a751 and the orders show for me now in testing. closing this, please reopen if still an issue (taking the changes live later today)

**Comment by romeshomey** [comment]
roddy-dermody, this issue seems to have presented itself again.  I currently have orders in 4 markets that show up at DEx but not at counterparty.io.

https://xcpdex.com/XCPCARD
https://xcpdex.com/SATOSHICARD
https://xcpdex.com/GENESISCARD
https://xcpdex.com/SHAPESHIFTCD

The markets on counterwallet.io show ZERO buy orders but there are several orders that show on DEx including orders from other traders, theirs however don't show up at counterwallet.io either.

So, just an FYI that somehow this issue has presented itself again.
